### GET users
GET http://localhost:3000/

### GET users
GET http://localhost:3000/cart/100

### GET users
GET http://localhost:3000/cart/101

### GET users
GET http://localhost:3000/cart/102

### GET users, cart does not exists
GET http://localhost:3000/cart/999

### GET users, url does not exists
GET http://localhost:3000/cart/999/hello

### GET ticket
GET http://localhost:3000/cart/100/ticket

### GET ticket
GET http://localhost:3000/cart/999/ticket